/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Institute {
    id: bigint;
    code: string;
    name: string;
    location: string;
}
export interface Employee {
    id: bigint;
    dob: string;
    instituteId: bigint;
    name: string;
    designation: Designation;
    joiningDate: string;
    employmentType: EmploymentType;
    employeeId: string;
    address: string;
    basicSalary: bigint;
}
export interface UserProfile {
    name: string;
    employeeId?: bigint;
}
export enum Designation {
    researchEngineer = "researchEngineer",
    professor = "professor",
    lecturer = "lecturer",
    humanResources = "humanResources",
    adminStaff = "adminStaff",
    officer = "officer",
    scientist = "scientist"
}
export enum EmploymentType {
    regular = "regular",
    temporary = "temporary"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEmployee(name: string, employeeId: string, instituteId: bigint, designation: Designation, employmentType: EmploymentType, joiningDate: string, address: string, dob: string, basicSalary: bigint): Promise<bigint>;
    addInstitute(name: string, code: string, location: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteEmployee(id: bigint): Promise<void>;
    deleteInstitute(id: bigint): Promise<void>;
    getAllEmployeesForInstitute(instituteId: bigint): Promise<Array<Employee>>;
    getAllInstitutes(): Promise<Array<Institute>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployee(id: bigint): Promise<Employee>;
    getEmployementForInstituteWithDesignation(instituteId: bigint, designation: Designation): Promise<Array<Employee>>;
    getInstitute(id: bigint): Promise<Institute>;
    getMyEmployeeData(): Promise<Employee | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    linkEmployeeToPrincipal(employeeId: bigint, principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateEmployee(id: bigint, name: string, employeeId: string, instituteId: bigint, designation: Designation, employmentType: EmploymentType, joiningDate: string, address: string, dob: string, basicSalary: bigint): Promise<void>;
    updateInstitute(id: bigint, name: string, code: string, location: string): Promise<void>;
}
import type { Designation as _Designation, Employee as _Employee, EmploymentType as _EmploymentType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEmployee(arg0: string, arg1: string, arg2: bigint, arg3: Designation, arg4: EmploymentType, arg5: string, arg6: string, arg7: string, arg8: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, arg1, arg2, to_candid_Designation_n1(this._uploadFile, this._downloadFile, arg3), to_candid_EmploymentType_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, arg1, arg2, to_candid_Designation_n1(this._uploadFile, this._downloadFile, arg3), to_candid_EmploymentType_n3(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addInstitute(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addInstitute(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInstitute(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteEmployee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteInstitute(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInstitute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInstitute(arg0);
            return result;
        }
    }
    async getAllEmployeesForInstitute(arg0: bigint): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeesForInstitute(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeesForInstitute(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInstitutes(): Promise<Array<Institute>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstitutes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstitutes();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: bigint): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_Employee_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_Employee_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployementForInstituteWithDesignation(arg0: bigint, arg1: Designation): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployementForInstituteWithDesignation(arg0, to_candid_Designation_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployementForInstituteWithDesignation(arg0, to_candid_Designation_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInstitute(arg0: bigint): Promise<Institute> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstitute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstitute(arg0);
            return result;
        }
    }
    async getMyEmployeeData(): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmployeeData();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmployeeData();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkEmployeeToPrincipal(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkEmployeeToPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkEmployeeToPrincipal(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateEmployee(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: Designation, arg5: EmploymentType, arg6: string, arg7: string, arg8: string, arg9: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, arg1, arg2, arg3, to_candid_Designation_n1(this._uploadFile, this._downloadFile, arg4), to_candid_EmploymentType_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, arg1, arg2, arg3, to_candid_Designation_n1(this._uploadFile, this._downloadFile, arg4), to_candid_EmploymentType_n3(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateInstitute(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstitute(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstitute(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Designation_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Designation): Designation {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_EmploymentType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmploymentType): EmploymentType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId: [] | [bigint];
}): {
    name: string;
    employeeId?: bigint;
} {
    return {
        name: value.name,
        employeeId: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    dob: string;
    instituteId: bigint;
    name: string;
    designation: _Designation;
    joiningDate: string;
    employmentType: _EmploymentType;
    employeeId: string;
    address: string;
    basicSalary: bigint;
}): {
    id: bigint;
    dob: string;
    instituteId: bigint;
    name: string;
    designation: Designation;
    joiningDate: string;
    employmentType: EmploymentType;
    employeeId: string;
    address: string;
    basicSalary: bigint;
} {
    return {
        id: value.id,
        dob: value.dob,
        instituteId: value.instituteId,
        name: value.name,
        designation: from_candid_Designation_n10(_uploadFile, _downloadFile, value.designation),
        joiningDate: value.joiningDate,
        employmentType: from_candid_EmploymentType_n12(_uploadFile, _downloadFile, value.employmentType),
        employeeId: value.employeeId,
        address: value.address,
        basicSalary: value.basicSalary
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    researchEngineer: null;
} | {
    professor: null;
} | {
    lecturer: null;
} | {
    humanResources: null;
} | {
    adminStaff: null;
} | {
    officer: null;
} | {
    scientist: null;
}): Designation {
    return "researchEngineer" in value ? Designation.researchEngineer : "professor" in value ? Designation.professor : "lecturer" in value ? Designation.lecturer : "humanResources" in value ? Designation.humanResources : "adminStaff" in value ? Designation.adminStaff : "officer" in value ? Designation.officer : "scientist" in value ? Designation.scientist : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    regular: null;
} | {
    temporary: null;
}): EmploymentType {
    return "regular" in value ? EmploymentType.regular : "temporary" in value ? EmploymentType.temporary : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Designation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Designation): _Designation {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EmploymentType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): _EmploymentType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId?: bigint;
}): {
    name: string;
    employeeId: [] | [bigint];
} {
    return {
        name: value.name,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Designation): {
    researchEngineer: null;
} | {
    professor: null;
} | {
    lecturer: null;
} | {
    humanResources: null;
} | {
    adminStaff: null;
} | {
    officer: null;
} | {
    scientist: null;
} {
    return value == Designation.researchEngineer ? {
        researchEngineer: null
    } : value == Designation.professor ? {
        professor: null
    } : value == Designation.lecturer ? {
        lecturer: null
    } : value == Designation.humanResources ? {
        humanResources: null
    } : value == Designation.adminStaff ? {
        adminStaff: null
    } : value == Designation.officer ? {
        officer: null
    } : value == Designation.scientist ? {
        scientist: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmploymentType): {
    regular: null;
} | {
    temporary: null;
} {
    return value == EmploymentType.regular ? {
        regular: null
    } : value == EmploymentType.temporary ? {
        temporary: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
